sudo: false

language: python

python:
  - 3.9

install:
  - pip install -r requirements-test.txt
  - pip install codecov

script:
  - pytest tests --cov=rudalle

after_success:
  - bash <(curl -s https://codecov.io/bash)
